import Link from 'next/link';
import {requireViewer} from '@/lib/auth/viewer';
import {createClient} from '@/lib/supabase/server';
import {assetKinds,assetStatuses,pageNumber} from '@/features/assets/model';
import {AssetLinkForm} from '@/features/assets/ticket-link-form';
export default async function AssetsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string;ticket?:string}>}) {
 const viewer=await requireViewer();const staff=viewer.role!=='end_user';const params=await searchParams;const q=(params.q??'').trim().slice(0,100);const page=pageNumber(params.page);const status=Object.hasOwn(assetStatuses,params.status??'')?params.status as keyof typeof assetStatuses:'';const db=await createClient();
 let query=db.from('assets').select('*',{count:'exact'}).eq('organization_id',viewer.organizationId);
 if(q)query=query.textSearch('search_document',q,{type:'websearch',config:'simple'});
 if(status)query=query.eq('status',status);
 const {data,error,count}=await query.order('updated_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 const ticket=staff&&/^[0-9a-f-]{36}$/i.test(params.ticket??'')?params.ticket:null;
 const ticketR=ticket?await db.from('tickets').select('id,ticket_number').eq('organization_id',viewer.organizationId).eq('id',ticket).maybeSingle():null;
 const href=(n:number)=>`/app/assets?${new URLSearchParams({q,status,page:String(n),...(ticket?{ticket}:{})})}`;
 return <div className={staff?'page':'portal-page'}><header className="page-header"><div><span className="page-eyebrow">{viewer.organizationName}</span><h1>{staff?'Assets':'My equipment'}</h1><p>{staff?'Track equipment, ownership and service history.':'Equipment assigned to you by your IT team.'}</p></div>{staff&&<Link className="button button-primary" href="/app/assets/new">Add asset</Link>}</header>{ticketR?.data&&<p className="alert">Choose equipment to link to <Link href={`/app/tickets/${ticket}`}>Ticket #{ticketR.data.ticket_number}</Link>.</p>}<form className="queue-filters" role="search"><label className="field">Search name, tag or serial number<input className="input" name="q" defaultValue={q} maxLength={100}/></label><label className="field">Lifecycle<select className="input" name="status" defaultValue={status}><option value="">All states</option>{Object.entries(assetStatuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{ticket&&<input type="hidden" name="ticket" value={ticket}/>}<button className="button button-secondary">Search assets</button></form>
 {error?<div className="alert alert-error" role="alert">Assets could not load. <Link href={href(page)}>Try again</Link></div>:data?.length?<><p className="muted">{count} asset{count===1?'':'s'} · Page {page}</p><div className="table-region" role="region" aria-label="Asset inventory" tabIndex={0}><table className="table responsive-table"><thead><tr><th scope="col">Asset</th><th scope="col">Type</th><th scope="col">Lifecycle</th><th scope="col">Model</th>{ticketR?.data&&<th scope="col">Ticket link</th>}</tr></thead><tbody>{data.map(a=><tr key={a.id}><td data-label="Asset"><Link href={`/app/assets/${a.id}`}>{a.name}</Link><div className="muted">{a.tag}</div></td><td data-label="Type">{assetKinds[a.kind]}</td><td data-label="Lifecycle"><span className="badge">{assetStatuses[a.status]}</span></td><td data-label="Model">{a.model??'Not set'}</td>{ticketR?.data&&<td data-label="Ticket link"><AssetLinkForm ticketId={ticketR.data.id} asset={a} link/></td>}</tr>)}</tbody></table></div></>:<div className="empty-state"><strong>{q||status?'No matching assets':staff?'No assets yet':'No equipment assigned'}</strong><p>{staff?'Add equipment to start keeping its service history.':'Your IT team will add equipment here when it is assigned to you.'}</p></div>}
 {!error&&<nav className="notification-pagination" aria-label="Asset pages">{page>1&&<Link href={href(page-1)}>Previous</Link>}{page*25<(count??0)&&<Link href={href(page+1)}>Next</Link>}</nav>}</div>;
}
