import { LiveSearchForm } from '@/components/ui/live-search-form';
import { pageNumber } from '@/lib/pagination';
import { normalizeSearch, SEARCH_HINT, SEARCH_LIMIT } from '@/lib/search';
import Link from 'next/link';
import {requireViewer} from '@/lib/auth/viewer';
import {createClient} from '@/lib/supabase/server';
import {assetKinds,assetStatuses} from '@/features/assets/model';
import {AssetLinkForm} from '@/features/assets/ticket-link-form';
export default async function AssetsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string;ticket?:string}>}) {
 const viewer=await requireViewer();const staff=viewer.role!=='end_user';const params=await searchParams;const q=normalizeSearch(params.q);const page=pageNumber(params.page);const status=typeof params.status==='string'&&Object.hasOwn(assetStatuses,params.status)?params.status as keyof typeof assetStatuses:'';const db=await createClient();
 const source=q?db.rpc('search_assets',{target_organization_id:viewer.organizationId,search_text:q},{count:'exact'}):db.from('assets');
 let query=source.select('*',{count:'exact'}).eq('organization_id',viewer.organizationId);
 if(!staff)query=query.eq('assigned_user_id',viewer.id);
 if(status)query=query.eq('status',status);
 const {data,error,count}=await query.order('updated_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 const ticket=staff&&/^[0-9a-f-]{36}$/i.test(params.ticket??'')?params.ticket:null;
 const ticketR=ticket?await db.from('tickets').select('id,ticket_number').eq('organization_id',viewer.organizationId).eq('id',ticket).maybeSingle():null;
 const href=(n:number)=>`/app/assets?${new URLSearchParams({q,status,page:String(n),...(ticket?{ticket}:{})})}`;
 const clearHref=ticket?`/app/assets?${new URLSearchParams({ticket})}`:'/app/assets';
 return <div className={staff?'page':'portal-page'}><header className="page-header"><div><span className="page-eyebrow">{viewer.organizationName}</span><h1>{staff?'Assets':'My equipment'}</h1><p>{staff?'Track equipment, ownership and service history.':'Equipment assigned to you by your IT team.'}</p></div>{staff&&<div className="page-header-actions"><Link className="button button-secondary" href="/app/assets/import">Import spreadsheet</Link><Link className="button button-primary" href="/app/assets/new">Add asset</Link></div>}</header>{ticketR?.data&&<p className="alert">Choose equipment to link to <Link href={`/app/tickets/${ticket}`}>Ticket #{ticketR.data.ticket_number}</Link>.</p>}<LiveSearchForm action="/app/assets" className="queue-filters" label="Search assets" resultSummary={error ? 'Assets could not load. Use Search to try again.' : `${count ?? 0} matching assets. Page ${page}.`}><label className="field">Search name, tag, serial number or model<input className="input" name="q" type="search" defaultValue={q} maxLength={SEARCH_LIMIT} aria-describedby="asset-search-hint" placeholder="12345 or HP 850"/></label><label className="field">Lifecycle<select className="input" name="status" defaultValue={status}><option value="">All states</option>{Object.entries(assetStatuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{ticket&&<input type="hidden" name="ticket" value={ticket}/>}<button className="button button-secondary">Search assets</button>{(q||status)&&<Link className="button button-quiet queue-clear" href={clearHref}>Clear filters</Link>}</LiveSearchForm><p className="muted" id="asset-search-hint">{SEARCH_HINT}</p>
 {error?<div className="alert alert-error" role="alert">Assets could not load. <Link className="button button-secondary" href={href(page)}>Try again</Link></div>:data?.length?<><p className="muted">{count} asset{count===1?'':'s'}{q?` matching “${q}”`:null} · Page {page}</p><div className="table-region" role="region" aria-label="Asset inventory" tabIndex={0}><table className="table responsive-table table-nowrap"><thead><tr><th scope="col">Asset</th><th scope="col">Serial number</th><th scope="col">Type</th><th scope="col">Lifecycle</th><th scope="col">Model</th>{ticketR?.data&&<th scope="col">Ticket link</th>}</tr></thead><tbody>{data.map(a=><tr key={a.id}><td data-label="Asset"><Link href={`/app/assets/${a.id}`}>{a.name}</Link><div className="muted">{a.tag}</div></td><td data-label="Serial number">{a.serial_number??'Not set'}</td><td data-label="Type">{assetKinds[a.kind]}</td><td data-label="Lifecycle"><span className="badge">{assetStatuses[a.status]}</span></td><td data-label="Model">{a.model??'Not set'}</td>{ticketR?.data&&<td data-label="Ticket link"><AssetLinkForm ticketId={ticketR.data.id} asset={a} link/></td>}</tr>)}</tbody></table></div></>:<div className="empty-state"><strong>{q||status?'No matching assets':staff?'No assets yet':'No equipment assigned'}</strong><p>{q||status?'Try a shorter name or serial-number fragment, or clear the filters.':staff?'Add equipment to start keeping its service history.':'Your IT team will add equipment here when it is assigned to you.'}</p></div>}
 {!error&&<nav className="notification-pagination" aria-label="Asset pages">{page>1&&<Link className="button button-secondary" href={href(page-1)}>Previous</Link>}{page*25<(count??0)&&<Link className="button button-secondary" href={href(page+1)}>Next</Link>}</nav>}</div>;
}
