import {redirect} from "next/navigation";
import { signOut } from "../../actions";
import { bootstrapOrganization } from "../actions";
import { createClient } from "@/lib/supabase/server";

type Props = { searchParams: Promise<{ error?: string }> };

export default async function UnassignedPage({ searchParams }: Props) {
  const message = await searchParams;
  const supabase = await createClient(); const { data } = await supabase.auth.getClaims();
  if(data?.claims?.sub){const {data: access}=await supabase.rpc("platform_access");if(access && access!=="none")redirect("/platform");}
  const suggestedName = typeof data?.claims?.user_metadata === "object" && data.claims.user_metadata && "display_name" in data.claims.user_metadata ? String(data.claims.user_metadata.display_name ?? "") : "";
  return <section className="auth-card auth-card-wide"><div className="onboarding-progress" aria-label="Signup progress"><span className="is-complete">✓</span><i/><span className="is-complete">✓</span><i/><span className="is-current">3</span></div><span className="page-eyebrow">Organization setup</span><h1>Create your workspace</h1><p className="auth-intro">Tell us about your organization. You’ll become its first administrator and can invite your team next.</p><form action={bootstrapOrganization} className="stack">{message.error && <div className="alert alert-error" role="alert">{message.error}</div>}<div className="field"><label htmlFor="organizationName">Organization name</label><input className="input" id="organizationName" name="organizationName" autoComplete="organization" required minLength={2} maxLength={120} placeholder="Acme Company" /></div><div className="field"><label htmlFor="organizationSlug">Workspace identifier</label><div className="input-prefix"><span aria-hidden="true">fixxflow.app/</span><input id="organizationSlug" name="organizationSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={2} maxLength={63} aria-describedby="slug-hint" placeholder="acme-company" required /></div><p className="form-note" id="slug-hint">Use lowercase letters, numbers, and hyphens. This uniquely identifies your workspace.</p></div><div className="field"><label htmlFor="administratorName">Administrator name</label><input className="input" id="administratorName" name="administratorName" autoComplete="name" defaultValue={suggestedName} required maxLength={120} /></div><div className="onboarding-summary"><strong>Your workspace includes</strong><ul><li>Your administrator account</li><li>An IT Support team</li><li>Starter ticket categories</li></ul></div><button className="button button-primary" type="submit">Create organization</button></form><form action={signOut} className="auth-secondary-action"><button className="link-button" type="submit">Sign out and finish later</button></form></section>;
}
