import Link from "next/link";
import { notFound } from "next/navigation";
import { requireViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { activityLabels, formatTicketDate, ticketPriorities, ticketStatuses } from "@/features/tickets/presentation";
import { AttachmentUpload } from "@/features/tickets/attachment-upload";
import { ConversationRefresh } from "@/features/tickets/conversation-refresh";
import { addTicketMessage, reopenTicket, updateTicket } from "../actions";

type Props = { params: Promise<{ ticketId: string }>; searchParams: Promise<{ error?: string; success?: string }> };
export default async function TicketPage({ params, searchParams }: Props) {
  const viewer = await requireViewer(); const { ticketId } = await params; const message = await searchParams; const supabase = await createClient();
  const { data: ticket } = await supabase.from("tickets").select("*").eq("organization_id", viewer.organizationId).eq("id", ticketId).maybeSingle(); if (!ticket || (viewer.role === "end_user" && ticket.requester_id !== viewer.id)) notFound();
  if (viewer.role === "end_user") {
    const employeeTicket = ticket;
    const [messagesR, attachmentsR, profilesR] = await Promise.all([supabase.from("ticket_messages").select("id, author_id, body, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at"), supabase.from("ticket_attachments").select("id, file_name, storage_path, size_bytes").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId), supabase.from("profiles").select("user_id, display_name").eq("organization_id", viewer.organizationId)]);
    const names = new Map((profilesR.data ?? []).map(p => [p.user_id, p.display_name]));
    const paths = (attachmentsR.data ?? []).map(a => a.storage_path);
    const { data: signed } = paths.length ? await supabase.storage.from("ticket-attachments").createSignedUrls(paths, 3600) : { data: [] };
    const urls = new Map((signed ?? []).map(v => [v.path, v.signedUrl ?? undefined]));
    const canReopen = employeeTicket.status === "resolved" || employeeTicket.status === "closed";
    return <div className="portal-page portal-detail"><ConversationRefresh/><div className="portal-page-heading"><div><Link href="/app/tickets">← My tickets</Link><p className="portal-reference">Request #{employeeTicket.ticket_number}</p><h1>{employeeTicket.title}</h1><span className={`ticket-badge tone-${ticketStatuses[employeeTicket.status].tone}`}>{ticketStatuses[employeeTicket.status].label}</span></div></div>{message.error && <div className="alert alert-error page-alert" role="alert">{message.error}</div>}{message.success && <div className="alert alert-success page-alert" role="status">{message.success} Request #{employeeTicket.ticket_number} is saved here.</div>}<section className="portal-detail-card"><h2>Your request</h2><p className="ticket-description">{employeeTicket.description}</p><p className="muted">Sent {formatTicketDate(employeeTicket.created_at)}</p></section><section className="portal-detail-card"><h2>Conversation</h2><div className="conversation">{messagesR.data?.length ? messagesR.data.map(m => <article className="message" key={m.id}><header><strong>{m.author_id === viewer.id ? "You" : names.get(m.author_id) ?? "IT support"}</strong><time>{formatTicketDate(m.created_at)}</time></header><p>{m.body}</p></article>) : <p className="muted">No replies yet. IT will respond here.</p>}</div>{canReopen ? <form action={reopenTicket}><input type="hidden" name="ticketId" value={employeeTicket.id}/><button className="button button-secondary">Reopen request</button></form> : <form action={addTicketMessage} className="message-form"><input type="hidden" name="ticketId" value={employeeTicket.id}/><label htmlFor="reply-body">Reply to IT</label><textarea className="input textarea" id="reply-body" name="body" required rows={4} maxLength={20000} placeholder="Write your message"/><button className="button button-primary">Send reply</button></form>}</section><section className="portal-detail-card"><h2>Attachments</h2><AttachmentUpload organizationId={viewer.organizationId} ticketId={employeeTicket.id} userId={viewer.id}/><div className="attachment-list">{attachmentsR.data?.map(a => <a key={a.id} href={urls.get(a.storage_path)} target="_blank" rel="noreferrer">{a.file_name} · {Math.ceil(a.size_bytes / 1024)} KB</a>)}{!attachmentsR.data?.length && <p className="muted">No files attached.</p>}</div></section></div>;
  }
  const [profilesR, membershipsR, teamsR, categoriesR, subsR, locationsR, messagesR, attachmentsR, activityR] = await Promise.all([
    supabase.from("profiles").select("user_id, display_name").eq("organization_id", viewer.organizationId), supabase.from("organization_memberships").select("user_id, role, status").eq("organization_id", viewer.organizationId).eq("status", "active"), supabase.from("teams").select("id, name").eq("organization_id", viewer.organizationId), supabase.from("ticket_categories").select("id, name").eq("organization_id", viewer.organizationId), supabase.from("ticket_subcategories").select("id, category_id, name").eq("organization_id", viewer.organizationId), supabase.from("locations").select("id, name").eq("organization_id", viewer.organizationId), supabase.from("ticket_messages").select("id, author_id, kind, body, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at"), supabase.from("ticket_attachments").select("id, file_name, storage_path, size_bytes, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at"), supabase.from("ticket_activity").select("id, actor_id, action, details, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at", { ascending: false }),
  ]);
  const names = new Map((profilesR.data ?? []).map(p => [p.user_id, p.display_name])); const workers = (membershipsR.data ?? []).filter(m => m.role !== "end_user");
  const paths = attachmentsR.data?.map(a => a.storage_path) ?? []; const { data: signed } = paths.length ? await supabase.storage.from("ticket-attachments").createSignedUrls(paths, 3600) : { data: [] }; const urls = new Map((signed ?? []).map(v => [v.path, v.signedUrl ?? undefined]));
  return <div className="page"><div className="ticket-topbar"><Link href="/app/tickets">← Back to tickets</Link><span>#{ticket.ticket_number}</span></div><header className="page-header ticket-heading"><div><div className="ticket-heading-badges"><span className={`ticket-badge tone-${ticketStatuses[ticket.status].tone}`}>{ticketStatuses[ticket.status].label}</span><span className={`ticket-badge tone-${ticketPriorities[ticket.priority].tone}`}>{ticketPriorities[ticket.priority].label}</span></div><h1>{ticket.title}</h1><p>Requested by {names.get(ticket.requester_id) ?? "Unknown"} · {formatTicketDate(ticket.created_at)}</p></div></header>{message.error && <div className="alert alert-error page-alert">{message.error}</div>}{message.success && <div className="alert alert-success page-alert">{message.success}</div>}
    <div className="ticket-layout"><main className="ticket-main"><section className="settings-card"><span className="section-kicker">Description</span><p className="ticket-description">{ticket.description}</p></section><section className="settings-card"><h2>Conversation</h2><div className="conversation">{messagesR.data?.length ? messagesR.data.map(m => <article key={m.id} className={`message ${m.kind === "internal_note" ? "message-note" : ""}`}><header><strong>{names.get(m.author_id) ?? "Team member"}</strong><span>{m.kind === "internal_note" ? "Internal note" : formatTicketDate(m.created_at)}</span></header><p>{m.body}</p></article>) : <p className="muted">No messages yet.</p>}</div><form action={addTicketMessage} className="message-form"><input type="hidden" name="ticketId" value={ticket.id}/><select className="input" name="kind" aria-label="Message type"><option value="reply">Public reply</option><option value="internal_note">Internal note</option></select><textarea className="input textarea" name="body" required rows={4} maxLength={20000} placeholder="Write a reply…"/><button className="button button-primary">Send message</button></form></section><section className="settings-card"><h2>Attachments</h2><AttachmentUpload organizationId={viewer.organizationId} ticketId={ticket.id} userId={viewer.id}/><div className="attachment-list">{attachmentsR.data?.map(a => <a key={a.id} href={urls.get(a.storage_path)} target="_blank" rel="noreferrer"><strong>{a.file_name}</strong><span>{Math.ceil(a.size_bytes / 1024)} KB · {formatTicketDate(a.created_at)}</span></a>)}{!attachmentsR.data?.length && <p className="muted">No attachments.</p>}</div></section></main>
      <aside className="ticket-sidebar"><form action={updateTicket} className="settings-card ticket-update"><h2>Ticket details</h2><input type="hidden" name="ticketId" value={ticket.id}/><label>Status<select className="input" name="status" defaultValue={ticket.status}>{Object.entries(ticketStatuses).map(([v,p]) => <option key={v} value={v}>{p.label}</option>)}</select></label><label>Priority<select className="input" name="priority" defaultValue={ticket.priority}>{Object.entries(ticketPriorities).map(([v,p]) => <option key={v} value={v}>{p.label}</option>)}</select></label><label>Technician<select className="input" name="assignedTechnicianId" defaultValue={ticket.assigned_technician_id ?? ""}><option value="">Unassigned</option>{workers.map(v => <option key={v.user_id} value={v.user_id}>{names.get(v.user_id) ?? "Team member"}</option>)}</select></label><label>Team<select className="input" name="teamId" defaultValue={ticket.team_id ?? ""}><option value="">Unassigned</option>{teamsR.data?.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Category<select className="input" name="categoryId" defaultValue={ticket.category_id ?? ""}><option value="">Not set</option>{categoriesR.data?.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Subcategory<select className="input" name="subcategoryId" defaultValue={ticket.subcategory_id ?? ""}><option value="">Not set</option>{subsR.data?.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Location<select className="input" name="locationId" defaultValue={ticket.location_id ?? ""}><option value="">Not set</option>{locationsR.data?.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Due date<input className="input" name="dueAt" type="datetime-local" defaultValue={ticket.due_at?.slice(0,16) ?? ""}/></label><button className="button button-primary">Save changes</button></form>
        <section className="settings-card activity"><h2>Activity</h2>{activityR.data?.map(a => <div key={a.id}><span className="activity-dot"/><p><strong>{a.actor_id ? names.get(a.actor_id) ?? "Team member" : "System"}</strong> {activityLabels[a.action] ?? a.action.replaceAll("_", " ")}<time>{formatTicketDate(a.created_at)}</time></p></div>)}</section></aside></div></div>;
}
