import { Timestamp } from '@/features/timezones/provider';
import { InventoryRequestPanel } from '@/features/inventory/request-panel';
import { inventoryAccess } from '@/features/inventory/access';
import { TicketDetailsForm } from "@/features/tickets/ticket-details-form";
import { profileLabels } from "@/features/lookups/labels";
import { activityAuthorName } from '@/features/tickets/authorship';
import { SlaPolicy } from "@/features/tickets/sla-policy-table";
import { HISTORY_PAGE_SIZE, recentMessages } from "@/features/conversations/history";
import { TicketAssets } from '@/features/assets/ticket-assets';
import { UsageEvent } from "@/features/product-analytics/usage-event";
import { SubmitButton } from "@/components/ui/submit-button";
import Link from "next/link";
import { SlaClock, SlaIndicator } from "@/features/tickets/sla-indicator";
import { notFound } from "next/navigation";
import { requireViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { activityLabels, ticketPriorities, ticketStatuses } from "@/features/tickets/presentation";
import { AttachmentUpload } from "@/features/tickets/attachment-upload";
import { ConversationRefresh } from "@/features/tickets/conversation-refresh";
import { ConversationTimeline } from "@/features/tickets/conversation-timeline";
import { MessageComposer } from "@/features/tickets/message-composer";
import { LinkedChatHistory } from "@/features/chat/linked-chat-history";
import { addTicketMessage, reopenTicket } from "../actions";

type Props = { params: Promise<{ ticketId: string }>; searchParams: Promise<{ error?: string; success?: string }> };
export default async function TicketPage({ params, searchParams }: Props) {
  const viewer = await requireViewer(); const { ticketId } = await params; const message = await searchParams; const supabase = await createClient();
  const { data: ticket, error: ticketError } = await supabase.from("tickets").select("*").eq("organization_id", viewer.organizationId).eq("id", ticketId).maybeSingle(); if (ticketError) throw new Error("Ticket could not be loaded. Please try again."); if (!ticket) notFound();
  if (viewer.role === "end_user" && ticket.requester_id !== viewer.id && !(ticket.request_kind === "inventory" && (await inventoryAccess(viewer)).manager)) notFound();
  if (viewer.role === "end_user") {
    const employeeTicket = ticket;
    const [messagesR, attachmentsR] = await Promise.all([supabase.from("ticket_messages").select("id, author_id, author_type, automation_name, kind, body, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).eq("kind", "reply").order("created_at", { ascending: false }).order("id", { ascending: false }).limit(HISTORY_PAGE_SIZE), supabase.from("ticket_attachments").select("id, file_name, storage_path, size_bytes").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at", { ascending: false }).order("id", { ascending: false }).limit(HISTORY_PAGE_SIZE)]);
    const profiles = await profileLabels(supabase, viewer.organizationId, (messagesR.data ?? []).map(message => message.author_id));
    const names = new Map(profiles.map(p => [p.user_id, p.display_name]));
    const paths = (attachmentsR.data ?? []).map(a => a.storage_path);
    const { data: signed } = paths.length ? await supabase.storage.from("ticket-attachments").createSignedUrls(paths, 3600) : { data: [] };
    const urls = new Map((signed ?? []).map(v => [v.path, v.signedUrl ?? undefined]));
    const canReopen = employeeTicket.requester_id === viewer.id && (employeeTicket.status === "resolved" || employeeTicket.status === "closed");
    return <div className="portal-page portal-detail">{viewer.usageSharing && <UsageEvent key={ticketId} event="ticket_viewed" surface="tickets" targetId={ticketId}/>}<ConversationRefresh/><div className="portal-page-heading"><div><Link className="button button-quiet page-back-link" href="/app/tickets">← My tickets</Link><p className="portal-reference">Request #{employeeTicket.ticket_number}</p><h1>{employeeTicket.title}</h1><span className={`ticket-badge tone-${ticketStatuses[employeeTicket.status].tone}`}>{ticketStatuses[employeeTicket.status].label}</span></div></div>{message.error && <div className="alert alert-error page-alert" role="alert">{message.error}</div>}{message.success && <div className="alert alert-success page-alert" role="status">{message.success} Request #{employeeTicket.ticket_number} is saved here.</div>}<InventoryRequestPanel ticketId={ticket.id}/><section className="portal-detail-card"><h2>Your request</h2><p className="ticket-description">{employeeTicket.description}</p><p className="muted">Sent <Timestamp value={employeeTicket.created_at}/></p></section><section className="portal-detail-card"><h2>Conversation</h2><Link className="button button-secondary" href={`/app/tickets/${ticket.id}/history`} target="_blank" rel="noopener noreferrer">Browse earlier messages (opens in a new tab)</Link><ConversationTimeline messages={recentMessages(messagesR.data ?? [])} names={names} viewerId={viewer.id} requesterId={ticket.requester_id} staff={false} error={!!messagesR.error}/>{canReopen ? <form action={reopenTicket}><input type="hidden" name="ticketId" value={employeeTicket.id}/><SubmitButton className="button button-secondary" pendingLabel="Reopening…">Reopen request</SubmitButton></form> : <MessageComposer key={ticket.id} ticketId={ticket.id} action={addTicketMessage} staff={false}/>}</section><LinkedChatHistory ticketId={employeeTicket.id} organizationId={viewer.organizationId} viewerId={viewer.id}/><section className="portal-detail-card"><h2>Attachments</h2><Link className="button button-secondary" href={`/app/tickets/${ticket.id}/history?view=files`}>Browse all files</Link><p className="muted">Ticket attachments are visible to the requester and IT staff.</p><AttachmentUpload organizationId={viewer.organizationId} ticketId={employeeTicket.id} userId={viewer.id}/>{attachmentsR.error && <p role="alert">Attachments could not load. Refresh to try again.</p>}<div className="attachment-list">{attachmentsR.data?.map(a => <a key={a.id} href={urls.get(a.storage_path)} target="_blank" rel="noreferrer">{a.file_name} · {Math.ceil(a.size_bytes / 1024)} KB</a>)}{!attachmentsR.error && !attachmentsR.data?.length && <p className="muted">No files attached.</p>}</div></section></div>;
  }
  const [messagesR, attachmentsR, activityR] = await Promise.all([
    supabase.from("ticket_messages").select("id, author_id, author_type, automation_name, kind, body, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at", { ascending: false }).order("id", { ascending: false }).limit(HISTORY_PAGE_SIZE), supabase.from("ticket_attachments").select("id, file_name, storage_path, size_bytes, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at", { ascending: false }).order("id", { ascending: false }).limit(HISTORY_PAGE_SIZE), supabase.from("ticket_activity").select("id, actor_id, action, details, created_at").eq("organization_id", viewer.organizationId).eq("ticket_id", ticketId).order("created_at", { ascending: false }).order("id", { ascending: false }).limit(HISTORY_PAGE_SIZE),
  ]);
  const profiles = await profileLabels(supabase, viewer.organizationId, [ticket.requester_id, ...(messagesR.data ?? []).map(row => row.author_id), ...(activityR.data ?? []).map(row => row.actor_id)]);
  const names = new Map(profiles.map(p => [p.user_id, p.display_name]));
  const paths = attachmentsR.data?.map(a => a.storage_path) ?? []; const { data: signed } = paths.length ? await supabase.storage.from("ticket-attachments").createSignedUrls(paths, 3600) : { data: [] }; const urls = new Map((signed ?? []).map(v => [v.path, v.signedUrl ?? undefined]));
  return <div className="page"><div className="ticket-topbar"><Link className="button button-quiet page-back-link" href="/app/tickets">← Back to tickets</Link><Link className="button button-secondary" href="#ticket-details">Edit ticket details</Link><span>#{ticket.ticket_number}</span></div><header className="page-header ticket-heading"><div><div className="ticket-heading-badges"><span className={`ticket-badge tone-${ticketStatuses[ticket.status].tone}`}>{ticketStatuses[ticket.status].label}</span><span className={`ticket-badge tone-${ticketPriorities[ticket.priority].tone}`}>{ticketPriorities[ticket.priority].label}</span></div><h1>{ticket.title}</h1><p>Requested by {names.get(ticket.requester_id) ?? "Unknown"} · <Timestamp value={ticket.created_at}/></p></div></header>{message.error && <div className="alert alert-error page-alert" role="alert">{message.error}</div>}{message.success && <div className="alert alert-success page-alert" role="status">{message.success}</div>}
    <div className="ticket-layout"><div className="ticket-main"><section className="settings-card"><span className="section-kicker">Description</span><p className="ticket-description">{ticket.description}</p></section><section className="settings-card"><h2>Conversation</h2><Link className="button button-secondary" href={`/app/tickets/${ticket.id}/history`} target="_blank" rel="noopener noreferrer">Browse earlier messages (opens in a new tab)</Link>{viewer.usageSharing && <UsageEvent key={ticketId} event="ticket_viewed" surface="tickets" targetId={ticketId}/>}<ConversationRefresh/><ConversationTimeline messages={recentMessages(messagesR.data ?? [])} names={names} viewerId={viewer.id} requesterId={ticket.requester_id} staff error={!!messagesR.error}/><MessageComposer key={ticket.id} ticketId={ticket.id} action={addTicketMessage}/></section><LinkedChatHistory ticketId={ticket.id} organizationId={viewer.organizationId} viewerId={viewer.id}/><section className="settings-card"><h2>Attachments</h2><Link className="button button-secondary" href={`/app/tickets/${ticket.id}/history?view=files`}>Browse all files</Link><p className="muted">Ticket attachments are visible to the requester and IT staff.</p><AttachmentUpload organizationId={viewer.organizationId} ticketId={ticket.id} userId={viewer.id}/>{attachmentsR.error && <p role="alert">Attachments could not load. Refresh to try again.</p>}<div className="attachment-list">{attachmentsR.data?.map(a => <a key={a.id} href={urls.get(a.storage_path)} target="_blank" rel="noreferrer"><strong>{a.file_name}</strong><span>{Math.ceil(a.size_bytes / 1024)} KB · <Timestamp value={a.created_at}/></span></a>)}{!attachmentsR.error && !attachmentsR.data?.length && <p className="muted">No attachments.</p>}</div></section></div>
      <aside className="ticket-sidebar"><InventoryRequestPanel ticketId={ticket.id}/><TicketAssets ticketId={ticket.id}/><section className="settings-card"><h2>Service levels</h2><SlaClock initialNow={new Date().getTime()}><SlaIndicator ticket={ticket}/></SlaClock><p className="muted">Calendar hours · Includes nights and weekends. Waiting and on-hold time counts.</p><details><summary>SLA targets</summary><SlaPolicy/><p className="muted">Priority changes adjust unfinished targets from creation. Reopening resumes the original resolution deadline.</p></details></section><TicketDetailsForm key={ticket.id} ticket={ticket} timeZone={viewer.timeZone}/>
        <section className="settings-card activity"><h2>Activity</h2><Link className="button button-secondary" href={`/app/tickets/${ticket.id}/history?view=activity`}>Browse all activity</Link>{activityR.error && <p role="alert">Activity could not load. Refresh to try again.</p>}{activityR.data?.map(a => <div key={a.id}><span className="activity-dot"/><p><strong>{activityAuthorName(a.actor_id, a.details, names)}</strong> {activityLabels[a.action] ?? a.action.replaceAll("_", " ")}{a.action === "automatically_routed" && a.details && typeof a.details === "object" && !Array.isArray(a.details) && typeof a.details.team_name === "string" ? `: ${a.details.team_name}` : ""}<time><Timestamp value={a.created_at}/></time></p></div>)}</section></aside></div></div>;
}
