import { ActionForm } from '@/components/ui/action-form';
import { SubmitButton } from '@/components/ui/submit-button';
import { manageAutomation } from '@/app/app/administration/automations/actions';

export function RuleActions({id,name,version,enabled,archived=false}:{id:string;name:string;version:number;enabled:boolean;archived?:boolean}) {
  const hidden=(operation:string)=><><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="operation" value={operation}/></>;
  return <div className="automation-inline">
    {!archived&&<details className="settings-editor"><summary>{enabled?'Disable':'Enable'}<span className="sr-only"> {name}</span></summary><ActionForm action={manageAutomation} className="stack">{hidden(enabled?'disable':'enable')}<p>{enabled?'Stop this rule from starting new work.':'Enable this saved version? It can process eligible future events only when global processing is active.'}</p>{!enabled&&<label className="check-field"><input type="checkbox" name="confirmation" value={id} required/>Enable “{name}”</label>}<SubmitButton className="button button-secondary">{enabled?'Disable rule':'Enable rule'}</SubmitButton></ActionForm></details>}
    {!archived&&<details className="settings-editor"><summary>Duplicate<span className="sr-only"> {name}</span></summary><ActionForm action={manageAutomation} className="stack">{hidden('duplicate')}<div className="field"><label htmlFor={`copy-${id}`}>Name for the disabled copy</label><input id={`copy-${id}`} className="input" name="name" defaultValue={`${name.slice(0,113)} (copy)`} required maxLength={120}/></div><SubmitButton className="button button-secondary">Create disabled copy</SubmitButton></ActionForm></details>}
    {!archived&&<details className="settings-editor"><summary>Archive<span className="sr-only"> {name}</span>…</summary><ActionForm action={manageAutomation} className="stack">{hidden('archive')}<p id={`archive-${id}`}>Archive “{name}”? The rule will stop and leave the active list. Its versions and history will be retained.</p><label className="check-field"><input type="checkbox" name="confirmation" value={id} required aria-describedby={`archive-${id}`}/>I confirm archiving {name}.</label><SubmitButton className="button button-danger" pendingLabel="Archiving…">Archive automation</SubmitButton><p className="muted">Close this section to cancel.</p></ActionForm></details>}
  </div>;
}
