import { SubmitButton } from "@/components/ui/submit-button";
import Link from "next/link";
import { requireViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { LiveChatQueue } from "@/features/chat/live-queue";
import { formatTicketDate } from "@/features/tickets/presentation";
import { startChat } from "./actions";

export default async function ChatPage({ searchParams }: { searchParams: Promise<{ error?: string; view?: string }> }) {
  const viewer = await requireViewer();
  const { error: message, view } = await searchParams;
  const supabase = await createClient();
  let query = supabase.from("chat_conversations").select("id, topic, requester_id, assigned_technician_id, status, ticket_id, updated_at").eq("organization_id", viewer.organizationId).order("updated_at", { ascending: false }).limit(100);
  if (viewer.role === "end_user") query = query.eq("requester_id", viewer.id);
  else if (view === "unassigned") query = query.is("assigned_technician_id", null).eq("status", "open");
  else if (view === "mine") query = query.eq("assigned_technician_id", viewer.id).eq("status", "open");
  else if (view !== "all") query = query.eq("status", "open");
  const [{ data: chats, error }, { data: profiles }] = await Promise.all([query, supabase.from("profiles").select("user_id, display_name").eq("organization_id", viewer.organizationId)]);
  const names = new Map((profiles ?? []).map(p => [p.user_id, p.display_name]));
  if (viewer.role === "end_user") return <div className="portal-page portal-form-page"><header className="portal-page-heading"><div><Link href="/app">← Home</Link><h1>Chat with IT</h1><p>Start a conversation and see replies here.</p></div></header>{message && <div className="alert alert-error page-alert" role="alert">{message}</div>}<form action={startChat} className="settings-card portal-request-form"><div className="field"><label htmlFor="chat-topic">What do you need help with?</label><input className="input" id="chat-topic" name="topic" required minLength={3} maxLength={180} placeholder="For example, I can’t connect to the VPN"/></div><div className="field"><label htmlFor="chat-first-message">Your message</label><textarea className="input textarea" id="chat-first-message" name="message" required rows={4} maxLength={20000} placeholder="Tell IT what is happening"/></div><SubmitButton className="button button-primary">Start chat</SubmitButton></form><section className="chat-history-list"><h2>Previous conversations</h2>{error ? <p role="alert">Conversations could not be loaded. Refresh to try again.</p> : chats?.length ? <ul>{chats.map(chat => <li key={chat.id}><Link href={`/app/chat/${chat.id}`}><strong>{chat.topic}</strong><span>{chat.status === "open" ? "Open" : "Closed"} · {formatTicketDate(chat.updated_at)}</span></Link></li>)}</ul> : <p>No conversations yet.</p>}</section></div>;
  const activeView = ["mine", "unassigned", "all"].includes(view ?? "") ? view : "open";
  return <div className="page"><header className="page-header"><div><span className="page-eyebrow">IT support</span><h1>Live support</h1><p>Incoming conversations and active chats.</p></div><LiveChatQueue organizationId={viewer.organizationId}/></header><nav className="queue-views" aria-label="Chat views"><Link href="/app/chat" aria-current={activeView === "open" ? "page" : undefined}>Open</Link><Link href="/app/chat?view=unassigned" aria-current={activeView === "unassigned" ? "page" : undefined}>Unassigned</Link><Link href="/app/chat?view=mine" aria-current={activeView === "mine" ? "page" : undefined}>My chats</Link><Link href="/app/chat?view=all" aria-current={activeView === "all" ? "page" : undefined}>History</Link></nav>{error ? <div className="alert alert-error" role="alert">Conversations could not be loaded. Refresh to try again.</div> : chats?.length ? <ul className="chat-queue-list">{chats.map(chat => <li key={chat.id}><Link href={`/app/chat/${chat.id}`}><span className="chat-queue-topic"><strong>{chat.topic}</strong><small>{names.get(chat.requester_id) ?? "Employee"} · {formatTicketDate(chat.updated_at)}</small></span><span>{chat.assigned_technician_id ? names.get(chat.assigned_technician_id) ?? "Assigned" : "Unassigned"}</span><span className={`ticket-badge tone-${chat.status === "open" ? "blue" : "slate"}`}>{chat.status === "open" ? "Open" : "Closed"}</span>{chat.ticket_id && <span className="chat-linked-indicator">Linked ticket</span>}</Link></li>)}</ul> : <div className="empty-state"><strong>No conversations in this view</strong><p>New chats will appear here as employees reach IT.</p></div>}</div>;
}
