-- Read-only public/private application schema fingerprints. No user row content.
-- Exclude PG18-only named NOT NULL constraints; column not_null is compared on both engines.
with objects as (
 select 'column' kind,n.nspname||'.'||c.relname||'.'||a.attname key,
 jsonb_build_object('type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid))::text definition
 from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('public','private') and c.relkind in ('r','p','v') and a.attnum>0 and not a.attisdropped
 union all select 'table',n.nspname||'.'||c.relname,jsonb_build_object('kind',c.relkind,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity)::text from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p','v')
 union all select 'constraint',n.nspname||'.'||c.relname||'.'||x.conname,pg_get_constraintdef(x.oid) from pg_constraint x join pg_class c on c.oid=x.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and x.contype<>'n'
 union all select 'index',n.nspname||'.'||c.relname,pg_get_indexdef(c.oid) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='i'
 union all select 'trigger',n.nspname||'.'||c.relname||'.'||t.tgname,pg_get_triggerdef(t.oid)||':'||t.tgenabled::text from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and not t.tgisinternal
 union all select 'policy',schemaname||'.'||tablename||'.'||policyname,jsonb_build_object('permissive',permissive,'roles',roles,'cmd',cmd,'qual',qual,'check',with_check)::text from pg_policies where schemaname in ('public','private')
 union all select 'function',n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')',jsonb_build_object('source',p.prosrc,'return',pg_get_function_result(p.oid),'definer',p.prosecdef,'volatility',p.provolatile,'config',p.proconfig,'language',l.lanname,'strict',p.proisstrict)::text from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname in ('public','private') and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')
 union all select 'enum',n.nspname||'.'||t.typname,string_agg(e.enumlabel,',' order by e.enumsortorder) from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname in ('public','private') group by n.nspname,t.typname
 union all select 'table_grant',n.nspname||'.'||c.relname||':'||coalesce(r.rolname,'PUBLIC')||':'||x.privilege_type,x.is_grantable::text from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(c.relacl) x left join pg_roles r on r.oid=x.grantee where n.nspname in ('public','private') and c.relkind in ('r','p','v') and (x.grantee=0 or r.rolname in ('anon','authenticated','service_role'))
 union all select 'column_grant',n.nspname||'.'||c.relname||'.'||a.attname||':'||coalesce(r.rolname,'PUBLIC')||':'||x.privilege_type,x.is_grantable::text from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(a.attacl) x left join pg_roles r on r.oid=x.grantee where n.nspname in ('public','private') and (x.grantee=0 or r.rolname in ('anon','authenticated','service_role'))
 union all select 'function_grant',n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||'):'||coalesce(r.rolname,'PUBLIC')||':'||x.privilege_type,x.is_grantable::text from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x left join pg_roles r on r.oid=x.grantee where n.nspname in ('public','private') and (x.grantee=0 or r.rolname in ('anon','authenticated','service_role')) and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')
) select kind,key,md5(definition) as fingerprint from objects order by kind,key;
